version: '3'
services:
  jupyter-notebook-gpu:
    container_name: autofj-jupyter
    image: "cschranz/gpu-jupyter:v1.4_cuda-11.2_ubuntu-20.04_python-only"
    volumes:
      - "./:/content/"
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia 
              capabilities: [gpu]
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    #command: nvidia-smi
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    command: bash -c 'pip install -q jupyter_http_over_ws && jupyter serverextension enable --py jupyter_http_over_ws && jupyter notebook --allow-root --NotebookApp.allow_origin=https://colab.research.google.com --port=8080 --NotebookApp.port_retries=0 --NotebookApp.password=""'
  
  jupyter-notebook-cpu:
    container_name: autofj-jupyter
    # build: 
    #   dockerfile: docker/jupyter.Dockerfile
    #   context: .
    image: "cschranz/gpu-jupyter:v1.4_cuda-11.2_ubuntu-20.04_python-only"
    ports:
      - "8080:8080"
    volumes:
      - "./:/content/"    
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    command: bash -c 'pip install -q jupyter_http_over_ws && jupyter serverextension enable --py jupyter_http_over_ws && jupyter notebook --allow-root --NotebookApp.allow_origin=https://colab.research.google.com --port=8080 --NotebookApp.port_retries=0 --NotebookApp.password=""'
